services:
  telethon-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telethon-core
    restart: unless-stopped
    volumes:
      - .:/app/
    environment:
      - TZ=UTC
    env_file:
      - .env
